
name: CI
on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      iam_token: ${{ steps.issue-iam-token.outputs.iam-token }}  # Указываем job output
    steps:
      - name: Получаем IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-key-id: ${{ secrets.YC_KEY_ID }}
          yc-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          yc-private-key: ${{ secrets.YC_PRIVATE_KEY }}

      - name: Debug IAM Token
        run: echo "${{ steps.issue-iam-token.outputs.iam-token }}"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: TEST
        run: echo "${{ needs.first-job.outputs.iam_token }}"
